# Generated by Django 4.1.6 on 2023-02-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_wheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckywheelslice',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='luckywheelslice',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField()),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucky_wheel.luckywheelslice')),
            ],
        ),
    ]
