# Generated by Django 4.1.7 on 2023-02-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaignstate_unique_together_and_more'),
        ('lucky_wheel', '0002_luckywheelslice_deleted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LuckyWheelSlice',
            new_name='LuckyWheel',
        ),
    ]
