# Generated by Django 4.1.7 on 2023-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('user_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('level', models.PositiveIntegerField(default=0)),
                ('played', models.PositiveIntegerField(default=0)),
                ('game_states', models.JSONField(default=dict)),
            ],
        ),
    ]
