# Generated by Django 4.1.5 on 2023-01-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=512)),
                ('date_time', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.action')),
            ],
        ),
    ]
