# Generated by Django 4.1.5 on 2023-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_vertical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignstate',
            old_name='state',
            new_name='criteria_state',
        ),
        migrations.AddField(
            model_name='campaignstate',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignstate',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='campaignstate',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='campaignstate',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
