# Generated by Django 4.1.5 on 2023-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_state_campaignstate_criteria_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcriteria',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
