# Generated by Django 4.1.5 on 2023-02-06 12:25

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_rewardcriteria_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rewardcriteria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='action',
            name='params',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=100, unique=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='params',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardcriteria',
            name='param',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rewardcriteria',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rewardcriteria',
            unique_together={('campaign', 'action', 'param')},
        ),
        migrations.RemoveField(
            model_name='rewardcriteria',
            name='count',
        ),
    ]
