# Generated by Django 4.1.7 on 2023-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_action_unique_together_action_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('vertical', 'title'), name='unique_vertical_and_title'),
        ),
        migrations.AddConstraint(
            model_name='vertical',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('name',), name='unique_name'),
        ),
    ]
