# Generated by Django 4.1.7 on 2023-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_action_unique_together_alter_vertical_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rewardcriteria',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rewardcriteria',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('campaign', 'action', 'param'), name='unique_campaign_action_param'),
        ),
    ]
