# Generated by Django 4.1.7 on 2023-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_rewardcriteria_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignstate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='campaignstate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('campaign', 'user_id'), name='unique_campaign_userid'),
        ),
    ]
