# Generated by Django 4.1.7 on 2023-02-22 19:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import eagle_eyes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaignstate_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignstate',
            old_name='criteria_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='rewardcriteria',
            name='index',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, storage=eagle_eyes.utils.AmazonS3ImageStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='threshold',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='rewardcriteria',
            name='hyperlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardcriteria',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignstate',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='campaigns.campaign'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('index', models.PositiveSmallIntegerField()),
                ('delay_days', models.PositiveSmallIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='campaigns.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'index')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('stage'), models.Model),
        ),
    ]
