# Generated by Django 4.1.7 on 2023-02-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_rename_criteria_state_campaignstate_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcriteria',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_criterias', to='campaigns.stage'),
        ),
    ]
