# Generated by Django 4.1.7 on 2023-02-22 20:00

from django.db import migrations


def set_criteria_stages(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RewardCriteria = apps.get_model('campaigns', 'RewardCriteria')
    Stage = apps.get_model('campaigns', 'Stage')
    for reward_criteria in RewardCriteria.objects.all():
        stage, _ = Stage.objects.get_or_create(
            campaign=reward_criteria.campaign,
            index=0
        )
        reward_criteria.stage = stage
        reward_criteria.save()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_rewardcriteria_stage'),
    ]

    operations = [
        migrations.RunPython(set_criteria_stages),
    ]
