# Generated by Django 4.1.7 on 2023-02-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20230222_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardcriteria',
            name='campaign',
        ),
        migrations.AlterField(
            model_name='rewardcriteria',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_criterias', to='campaigns.stage'),
        ),
    ]
