# Generated by Django 4.1.7 on 2023-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_rewardcriteria_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rewardcriteria',
            name='unique_campaign_action_param',
        ),
        migrations.AddConstraint(
            model_name='rewardcriteria',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('stage', 'action', 'param'), name='unique_stage_action_param'),
        ),
    ]
