# Generated by Django 4.1.7 on 2023-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_remove_rewardcriteria_unique_campaign_action_param_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
