# Generated by Django 4.1.7 on 2023-02-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_alter_stage_unique_together_and_more'),
        ('campaigns', '0016_stage_title'),
    ]

    operations = [
    ]
