# Generated by Django 4.1.7 on 2023-02-27 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import eagle_eyes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_merge_20230223_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, storage=eagle_eyes.utils.AmazonS3ImageStorage, upload_to='')),
                ('text_done', models.TextField()),
                ('text_undone', models.TextField()),
                ('percentage', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='campaigns.campaign')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('stage'), models.Model),
        ),
    ]
