# Generated by Django 4.1.7 on 2023-02-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaigncheckpoint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaigncheckpoint',
            unique_together={('campaign', 'percentage')},
        ),
    ]
