# Generated by Django 4.1.7 on 2023-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_remove_campaign_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lottery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
