# Generated by Django 4.1.7 on 2023-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_campaign_lottery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='lottery_date',
            field=models.DateField(null=True),
        ),
    ]
