# Generated by Django 4.1.7 on 2023-03-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_stage_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='delay',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
