# Generated by Django 4.1.7 on 2023-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_alter_campaign_lottery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncheckpoint',
            name='rewarded_chances',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
