# Generated by Django 4.1.7 on 2023-03-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_alter_stage_delay'),
        ('campaigns', '0023_campaigncheckpoint_rewarded_chances'),
    ]

    operations = [
    ]
