# Generated by Django 4.1.7 on 2023-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_merge_20230311_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='lottery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
