# Generated by Django 4.1.7 on 2023-03-12 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_alter_campaign_lottery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='delay',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
