# Generated by Django 4.1.7 on 2023-03-18 12:24

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_campaign_lottery_text_campaign_no_chance_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value_type', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float')], default='float', max_length=10)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='campaigns.action')),
            ],
            options={
                'unique_together': {('action', 'key')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('action_parameters'), models.Model),
        ),
    ]
