# Generated by Django 4.1.7 on 2023-03-19 06:29

from django.db import migrations


def add_action_parameters(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Action = apps.get_model('campaigns', 'Action')
    ActionParameter = apps.get_model('campaigns', 'ActionParameter')
    Event = apps.get_model('campaigns', 'Event')

    action_parameters = []
    for action in Action.objects.all():
        for key in action.params:
            # Get a sample event for the current action & parameter in order to determine parameter types
            sample_event = Event.objects.filter(action=action) \
                .exclude(**{f"params__{key}__isnull": True}).first()
            if sample_event and key in sample_event.params:
                param_type = type(sample_event.params[key])
            else:
                param_type = str
            action_parameters.append(ActionParameter(
                action=action,
                key=key,
                value_type=param_type.__name__
            ))
    ActionParameter.objects.bulk_create(action_parameters)


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0028_actionparameter'),
    ]

    operations = [
        migrations.RunPython(add_action_parameters),
    ]
