# Generated by Django 4.1.7 on 2023-03-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_auto_20230319_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='params',
        ),
    ]
