# Generated by Django 4.1.7 on 2023-03-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0030_remove_action_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionparameter',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='campaigns.action'),
        ),
    ]
