# Generated by Django 4.2 on 2023-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0031_alter_actionparameter_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reward_type',
            field=models.CharField(choices=[('LOTTERY', 'lottery'), ('INTERNET', 'internet')], default='INTERNET', max_length=20),
        ),
    ]
