# Generated by Django 4.2 on 2023-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0032_campaign_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='reward_type',
            field=models.CharField(choices=[('LOTTERY', 'lottery'), ('INTERNET', 'internet')], default='LOTTERY', max_length=20),
        ),
    ]
