# Generated by Django 4.2 on 2023-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_alter_campaign_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='progress_type',
            field=models.CharField(choices=[('STAGE_STATE', 'stage state'), ('REWARD_CRITERIA_STATE', 'reward criteria state'), ('REWARD_CRITERIA_VALUE', 'reward criteria value')], default='REWARD_CRITERIA_STATE', max_length=60),
        ),
    ]
