# Generated by Django 4.2 on 2023-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_campaign_progress_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('REGULAR', 'regular'), ('REFERRAL', 'referral'), ('REFEREE', 'referee')], default='REGULAR', max_length=60),
        ),
    ]
