# Generated by Django 4.2 on 2023-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0036_alter_campaign_progress_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
