# Generated by Django 4.2 on 2023-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0036_alter_campaign_progress_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='child_actions',
            field=models.ManyToManyField(blank=True, related_name='parent_actions', to='campaigns.action'),
        ),
    ]
