# Generated by Django 4.2 on 2023-05-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0037_action_child_actions'),
        ('campaigns', '0037_campaign_index'),
    ]

    operations = [
    ]
