# Generated by Django 4.2.1 on 2023-06-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0038_merge_0037_action_child_actions_0037_campaign_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='delay_days',
        ),
    ]
