# Generated by Django 4.2.1 on 2023-07-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0039_remove_stage_delay_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EngagementState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('state', models.JSONField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='general_processor.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_criterias', to='campaigns.action')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_criterias', to='general_processor.tracker')),
            ],
        ),
    ]
