# Generated by Django 4.2.1 on 2023-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
