# Generated by Django 4.2.1 on 2023-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_processor', '0002_alter_tracker_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementstate',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
