# Generated by Django 4.1.7 on 2023-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
