# Generated by Django 4.2 on 2023-05-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_alter_campaign_reward_type'),
        ('referral_reward', '0003_config_userreward_is_mci_userreward_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=100)),
                ('referee', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferralState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referral_reward.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('referee_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias', to='campaigns.action')),
                ('reward_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias', to='campaigns.rewardcriteria')),
            ],
        ),
    ]
