# Generated by Django 4.2 on 2023-05-13 21:35

from django.db import migrations, models
import eagle_eyes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('referral_reward', '0006_reward_description_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(null=True, storage=eagle_eyes.utils.AmazonS3ImageStorage, upload_to=''),
        ),
    ]
