# Generated by Django 4.2 on 2023-05-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_reward', '0007_alter_reward_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreward',
            name='checkpoint',
        ),
    ]
