# Generated by Django 4.2 on 2023-05-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_campaign_progress_type'),
        ('referral_reward', '0008_remove_userreward_checkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcriteria',
            name='referee_action',
        ),
        migrations.AddField(
            model_name='referralcriteria',
            name='referee_required_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias_required', to='campaigns.action'),
        ),
        migrations.AddField(
            model_name='referralcriteria',
            name='referee_rewarded_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias_rewarded', to='campaigns.action'),
        ),
    ]
