# Generated by Django 4.2 on 2023-05-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_reward', '0009_remove_referralcriteria_referee_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='auth_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
