# Generated by Django 4.1.7 on 2023-06-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0038_merge_0037_action_child_actions_0037_campaign_index'),
        ('referral_reward', '0010_userreward_auth_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.AlterField(
            model_name='referralcriteria',
            name='referee_required_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_reward_criterias_required', to='campaigns.action'),
        ),
        migrations.AlterField(
            model_name='referralcriteria',
            name='referee_rewarded_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_reward_criterias_rewarded', to='campaigns.action'),
        ),
        migrations.AlterField(
            model_name='referralcriteria',
            name='reward_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_reward_criterias', to='campaigns.rewardcriteria'),
        ),
        migrations.AlterField(
            model_name='referralstate',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_reward', to='referral_reward.referral'),
        ),
    ]
