# Generated by Django 4.2.1 on 2023-06-25 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referral_reward", "0011_delete_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralcriteria",
            name="referee_required_action",
        ),
        migrations.RemoveField(
            model_name="referralcriteria",
            name="referee_rewarded_action",
        ),
        migrations.RemoveField(
            model_name="referralcriteria",
            name="reward_criteria",
        ),
        migrations.RemoveField(
            model_name="referralstate",
            name="referral",
        ),
        migrations.DeleteModel(
            name="Referral",
        ),
        migrations.DeleteModel(
            name="ReferralCriteria",
        ),
        migrations.DeleteModel(
            name="ReferralState",
        ),
    ]
