# Generated by Django 4.2.3 on 2023-08-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0039_remove_stage_delay_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('start_xp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('user_id', models.CharField(primary_key=True, serialize=False)),
                ('XP', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('index', models.PositiveSmallIntegerField()),
                ('XP', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('hyperlink', models.URLField(blank=True, null=True)),
                ('has_limit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='campaigns.action')),
            ],
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosters', to='club.mission')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField()),
                ('mission_id', models.PositiveIntegerField()),
                ('vertical', models.CharField()),
                ('action', models.CharField()),
                ('earned_xp', models.PositiveIntegerField()),
                ('earned_points', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'date_time'], name='club_activi_user_id_80954b_idx')],
            },
        ),
    ]
