# Generated by Django 4.2.3 on 2023-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='has_limit',
            field=models.BooleanField(default=True),
        ),
    ]
