import os

# =============== Engagement Processing Config ===============
KAFKA_EVENT_TOPIC = os.getenv('KAFKA_EVENT_TOPIC')
KAFKA_ENGAGEMENT_CONSUMER_GROUP = os.getenv('KAFKA_ENGAGEMENT_CONSUMER_GROUP')
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS').split(",")
ENGAGEMENT_PROCESSOR_BATCH_SIZE = os.getenv('ENGAGEMENT_PROCESSOR_BATCH_SIZE')
ENGAGEMENT_PROCESSOR_BATCH_TIMEOUT_SECONDS = os.getenv('ENGAGEMENT_PROCESSOR_BATCH_TIMEOUT_SECONDS')

ADTRACE_AUTHORIZATION = os.getenv('ADTRACE_AUTHORIZATION')
ZAREBIN_APP_TOKEN = os.getenv('ZAREBIN_APP_TOKEN')
ENGAGEMENT_EVENT_TOKEN = os.getenv('ENGAGEMENT_EVENT_TOKEN')
ADTRACE_URL = os.getenv('ADTRACE_URL')
