import os
from django.utils.dateparse import parse_date

KAFKA_EVENT_TOPIC = os.getenv('KAFKA_EVENT_TOPIC')
KAFKA_EVENT_TOPIC_CONSUMER_GROUP = os.getenv('KAFKA_EVENT_TOPIC_CONSUMER_GROUP')
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS').split(",")
KAFKA_GAME_EVENT_CONSUMER_GROUP = os.getenv('KAFKA_GAME_EVENT_CONSUMER_GROUP', '')

AMAZON_S3_STORAGE_ACCESS_KEY = os.getenv('AMAZON_S3_STORAGE_ACCESS_KEY')
AMAZON_S3_STORAGE_SECRET_KEY = os.getenv('AMAZON_S3_STORAGE_SECRET_KEY')

EVENT_PROCESSOR_BATCH_SIZE = os.getenv('EVENT_PROCESSOR_BATCH_SIZE')
EVENT_PROCESSOR_BATCH_TIMEOUT_SECONDS = os.getenv('EVENT_PROCESSOR_BATCH_TIMEOUT_SECONDS')

CAMPAIGNS_DEPRECATION_DATE = parse_date(os.getenv('CAMPAIGNS_DEPRECATION_DATE')) \
    if os.getenv('CAMPAIGNS_DEPRECATION_DATE') else None
