# Generated by Django 4.2.1 on 2023-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('referrer_phone_number', models.CharField(max_length=20)),
                ('referee_phone_number', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('done_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
