# Generated by Django 4.2.1 on 2023-06-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='deleted_by_cascade',
        ),
    ]
