# Generated by Django 4.1.7 on 2023-06-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0038_merge_0037_action_child_actions_0037_campaign_index'),
        ('referral', '0002_remove_referral_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referral.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('referee_required_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias_required', to='campaigns.action')),
                ('referee_rewarded_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias_rewarded', to='campaigns.action')),
                ('reward_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_criterias', to='campaigns.rewardcriteria')),
            ],
        ),
    ]
