# Generated by Django 4.1.7 on 2023-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagleusers', '0002_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notary',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('user_id', models.CharField(max_length=36)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
