# Generated by Django 4.1.7 on 2023-06-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagleusers', '0003_notary'),
    ]

    operations = [
        migrations.RemoveField(model_name='notary', name='id',),
        migrations.AlterField(
            model_name='notary',
            name='user_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
